name: Deploy and OWASP ZAP baseline Scan

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  deploy:
    uses: securefdev/configs/.github/workflows/wrangler-deploy.yaml@master
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  scan:
    uses: securefdev/configs/.github/workflows/zap-baseline-scan.yaml@master
    needs: deploy
    with:
      production-url: https://securef.dev
