name: Security Checks

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  baseline:
    uses: securefdev/configs/.github/workflows/security-baseline.yaml@master

  semgrep:
    uses: securefdev/configs/.github/workflows/semgrep.yaml@master

  secret-scan:
    uses: securefdev/configs/.github/workflows/secret-scan.yaml@master
    with:
      configs-ref: master
